import { readFile, rm } from 'node:fs/promises'
import * as path from 'node:path'

import { afterEach, describe, expect, it, vi } from 'vitest'
import { z } from 'zod'

import { AniListClient, AniListClientError } from '../../electron/modules/watch-connectors/providers/anilist/anilist.client.js'
import { AniListConnector } from '../../electron/modules/watch-connectors/providers/anilist/anilist.connector.js'
import { aniListStatusFromNexus, mapAniListEntry, remoteStatusFromAniList } from '../../electron/modules/watch-connectors/providers/anilist/anilist.mapper.js'
import type { AniListListEntry } from '../../electron/modules/watch-connectors/providers/anilist/anilist.types.js'
import { SecureTokenStore, type TokenEncryption } from '../../electron/modules/watch-connectors/secure-token-store.js'
import { OAuthCallbackBroker, WatchAuthService, createOAuthSession, validateOAuthSession } from '../../electron/modules/watch-connectors/watch-auth.service.js'
import { WatchConnectorConfigurationService } from '../../electron/modules/watch-connectors/watch-connector.config.js'
import { WatchConnectorRegistry } from '../../electron/modules/watch-connectors/watch-connector.registry.js'
import type { WatchConnectorManager } from '../../electron/modules/watch-connectors/watch-connector.manager.js'
import type { WatchConnector } from '../../electron/modules/watch-connectors/watch-connector.types.js'
import { WatchConnectorsModule } from '../../electron/modules/watch-connectors/watch-connectors.module.js'
import { WatchSyncExecutor } from '../../electron/modules/watch-connectors/watch-sync-executor.js'
import { matchRemoteWatchEntry } from '../../electron/modules/watch-connectors/watch-sync-matcher.js'
import { WatchSyncPlanner } from '../../electron/modules/watch-connectors/watch-sync-planner.js'
import { createWatchEntry } from '../../electron/modules/watch-tracking/watch-history-normalizer.js'
import { NexusCore } from '../../src/core/nexus-core.js'
import type { RemoteMediaEntry, WatchSyncOperation, WatchSyncPlan } from '../../src/features/watch-connectors/connector.types.js'
import type { WatchEntry } from '../../src/features/watch-tracking/watch.types.js'

const temporaryFiles: string[] = []
afterEach(async () => { vi.restoreAllMocks(); vi.useRealTimers(); await Promise.all(temporaryFiles.splice(0).map((file) => rm(file, { force: true }))) })

const anilistEntry = (overrides: Partial<AniListListEntry> = {}): AniListListEntry => ({ completedAt: null, id: 77, media: { coverImage: { large: 'https://img.test/arcane.jpg', medium: null }, episodes: 12, format: 'TV', id: 42, idMal: 100, season: 'FALL', seasonYear: 2025, status: 'FINISHED', synonyms: ['Arcane 2'], title: { english: 'Arcane', native: null, romaji: 'Arcane', userPreferred: 'Arcane' }, updatedAt: 10 }, progress: 3, repeat: 0, score: 84, startedAt: { day: 2, month: 1, year: 2026 }, status: 'CURRENT', updatedAt: 20, ...overrides })
const remote = (overrides: Partial<RemoteMediaEntry> = {}): RemoteMediaEntry => ({ alternativeTitles: ['Arcane 2'], completedAt: null, coverImageUrl: null, episodeCount: 12, externalIds: { anilist: '42', myanimelist: '100' }, format: 'TV', mediaType: 'anime', progress: 3, provider: 'anilist', providerEntryId: '77', providerMediaId: '42', releaseYear: 2025, repeatCount: 0, score: 84, startedAt: null, status: 'current', title: 'Arcane', updatedAt: 20_000, ...overrides })
const local = (overrides: Partial<WatchEntry> = {}): WatchEntry => ({ ...createWatchEntry({ automatic: false, mediaType: 'anime', precision: 'watched-only', profileName: 'Default', provider: 'manual', status: 'in-progress', title: 'Arcane' }), externalIds: { anilist: '42' }, metadata: { releaseYear: 2025, remoteProgress: 3 }, ...overrides })

describe('OAuth sessions and secure token storage', () => {
  it('generates unpredictable state and accepts a matching custom-protocol callback', async () => { const broker = new OAuthCallbackBroker(); const session = createOAuthSession('anilist', 'nexus://oauth/anilist', 1_000); const pending = broker.waitForCode({ ...session, expiresAt: Date.now() + 5_000 }); expect(session.state).toHaveLength(43); expect(broker.handle(`nexus://oauth/anilist?code=abc&state=${session.state}`)).toBe(true); await expect(pending).resolves.toBe('abc') })
  it('rejects a callback with an invalid state', async () => { const broker = new OAuthCallbackBroker(); const session = createOAuthSession('anilist', 'nexus://oauth/anilist'); const pending = broker.waitForCode(session); broker.handle('nexus://oauth/anilist?code=abc&state=wrong'); await expect(pending).rejects.toThrow(/OAuth invalide/) })
  it('rejects expired OAuth sessions', () => { const session = createOAuthSession('anilist', 'nexus://oauth/anilist', 1_000); expect(() => validateOAuthSession(session, session.state, session.expiresAt + 1)).toThrow(/expir/) })
  it('encrypts, reads and deletes credentials without writing the token in clear text', async () => { const file = path.join(process.cwd(), `.watch-token-${crypto.randomUUID()}.json`); temporaryFiles.push(file); const encryption: TokenEncryption = { decrypt: (value) => Buffer.from(value).toString('utf8').split('').reverse().join(''), encrypt: (value) => Buffer.from(value.split('').reverse().join('')), isAvailable: () => true }; const store = new SecureTokenStore(file, encryption); const reference = await store.save('anilist', { accessToken: 'secret-access-token-value', expiresAt: 10_000, tokenType: 'Bearer' }); expect(await readFile(file, 'utf8')).not.toContain('secret-access-token-value'); await expect(store.read(reference)).resolves.toMatchObject({ accessToken: 'secret-access-token-value' }); await store.delete('anilist'); await expect(store.read(reference)).resolves.toBeNull() })
  it('refuses clear-text fallback when encryption is unavailable', async () => { const file = path.join(process.cwd(), `.watch-token-${crypto.randomUUID()}.json`); temporaryFiles.push(file); const unavailable: TokenEncryption = { decrypt: () => '', encrypt: () => new Uint8Array(), isAvailable: () => false }; await expect(new SecureTokenStore(file, unavailable).save('anilist', { accessToken: 'secret-access-token-value', expiresAt: null, tokenType: 'Bearer' })).rejects.toThrow(/indisponible/) })
  it('exchanges an authorization code without exposing it to the caller', async () => { const broker = new OAuthCallbackBroker(); const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ access_token: 'a-secure-token-long-enough', expires_in: 3_600, token_type: 'Bearer' }), { status: 200 })); const openExternal = vi.fn().mockImplementation(async (url: string) => { const authorize = new URL(url); broker.handle(`nexus://oauth/anilist?code=one-time-code&state=${authorize.searchParams.get('state') ?? ''}`) }); const auth = new WatchAuthService({ broker, fetcher, openExternal }); await expect(auth.authenticateAniList({ clientId: 'client', clientSecret: 'secret', redirectUri: 'nexus://oauth/anilist' })).resolves.toMatchObject({ accessToken: 'a-secure-token-long-enough', tokenType: 'Bearer' }); const sentBody = String((fetcher.mock.calls[0]?.[1] as RequestInit | undefined)?.body); expect(sentBody).toContain('one-time-code'); expect(openExternal.mock.calls[0]?.[0]).not.toContain('secret') })
})

describe('AniList client and mapping', () => {
  it('maps all AniList states without losing paused/repeating information', () => { expect(remoteStatusFromAniList('PAUSED')).toBe('paused'); expect(remoteStatusFromAniList('REPEATING')).toBe('repeating'); expect(aniListStatusFromNexus('completed')).toBe('COMPLETED'); expect(aniListStatusFromNexus('unknown')).toBeNull() })
  it('normalizes a remote list entry and keeps external IDs', () => { expect(mapAniListEntry(anilistEntry())).toMatchObject({ externalIds: { anilist: '42', myanimelist: '100' }, progress: 3, providerMediaId: '42', releaseYear: 2025, status: 'current', title: 'Arcane' }) })
  it('validates GraphQL responses at runtime', async () => { const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify({ data: { value: 4 } }), { status: 200 })); const client = new AniListClient('token', fetcher); await expect(client.query('query Test', {}, z.object({ value: z.number() }))).resolves.toEqual({ value: 4 }); expect(fetcher).toHaveBeenCalledOnce() })
  it('surfaces GraphQL and authentication errors', async () => { const graph = new AniListClient('token', vi.fn().mockResolvedValue(new Response(JSON.stringify({ errors: [{ message: 'Bad query' }] }), { status: 200 }))); await expect(graph.query('query', {}, z.object({}))).rejects.toThrow(/Bad query/); const auth = new AniListClient('token', vi.fn().mockResolvedValue(new Response(JSON.stringify({ errors: [{ message: 'Invalid', status: 401 }] }), { status: 401 }))); await expect(auth.query('query', {}, z.object({}))).rejects.toMatchObject({ status: 401 }) })
  it('honors rate limiting and retries reads only', async () => { const fetcher = vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({ errors: [{ message: 'slow', status: 429 }] }), { headers: { 'Retry-After': '0.001' }, status: 429 })).mockResolvedValueOnce(new Response(JSON.stringify({ data: { value: 1 } }), { status: 200 })); const client = new AniListClient('token', fetcher); await expect(client.query('query', {}, z.object({ value: z.number() }))).resolves.toEqual({ value: 1 }); expect(fetcher).toHaveBeenCalledTimes(2) })
  it('loads Viewer then paginates with the explicit AniList user ID', async () => { let page = 0; const query = vi.fn().mockImplementation(async (document: string, variables: Readonly<Record<string, unknown>>) => { if (document.includes('ViewerForNexus')) return { Viewer: { avatar: null, id: 9, name: 'Mathys' } }; expect(variables.userId).toBe(9); return { Page: { mediaList: [anilistEntry({ id: ++page })], pageInfo: { currentPage: page, hasNextPage: page < 2, lastPage: 2, total: 2 } } } }); const client = { query } as unknown as AniListClient; const connector = new AniListConnector(new WatchConnectorRegistry().get('anilist'), client); await expect(connector.pullHistory()).resolves.toHaveLength(2); expect(query).toHaveBeenCalledTimes(3) })
  it('rejects invalid progress and score before a mutation', async () => { const client = { mutate: vi.fn() } as unknown as AniListClient; const connector = new AniListConnector(new WatchConnectorRegistry().get('anilist'), client); await expect(connector.pushChange({ mediaId: '42', progress: -1, score: null, status: 'current' })).rejects.toThrow(/Progression/); await expect(connector.pushChange({ mediaId: '42', progress: 1, score: 101, status: 'current' })).rejects.toThrow(/Score/); expect(client.mutate).not.toHaveBeenCalled() })
})

describe('matching and synchronization planning', () => {
  it('matches exact external IDs before titles', () => { expect(matchRemoteWatchEntry(remote(), [local({ title: 'Different title' })])).toMatchObject({ confidence: 'exact' }) })
  it('uses alternative title and year as a high-confidence match', () => { const entry = local({ externalIds: {}, normalizedTitle: 'arcane 2', title: 'Arcane 2' }); expect(matchRemoteWatchEntry(remote(), [entry]).confidence).toBe('high') })
  it('rejects title matches with a different year', () => { expect(matchRemoteWatchEntry(remote(), [local({ externalIds: {}, metadata: { releaseYear: 1999 }, title: 'Arcane' })]).confidence).toBe('low') })
  it('keeps ambiguous matches out of automatic synchronization', () => { const entries = [local({ externalIds: {}, id: 'one' }), local({ externalIds: {}, id: 'two' })]; const { plan } = new WatchSyncPlanner().build({ connectorId: 'anilist', direction: 'pull', localEntries: entries, profileName: 'Default', remoteEntries: [remote()] }); expect(plan.operations[0]).toMatchObject({ included: false, type: 'unmatched' }) })
  it('plans pull creation and leaves unchanged entries skipped', () => { const planner = new WatchSyncPlanner(); expect(planner.build({ connectorId: 'anilist', direction: 'pull', localEntries: [], profileName: 'Default', remoteEntries: [remote()] }).plan.summary.createLocal).toBe(1); const unchanged = planner.build({ connectorId: 'anilist', direction: 'pull', localEntries: [local()], profileName: 'Default', remoteEntries: [remote()] }).plan; expect(unchanged.summary.unchanged).toBe(1) })
  it('protects manual corrections and reports progress divergence', () => { const planner = new WatchSyncPlanner(); const manual = planner.build({ connectorId: 'anilist', direction: 'pull', localEntries: [local({ manuallyEdited: true, status: 'completed' })], profileName: 'Default', remoteEntries: [remote()] }); expect(manual.conflicts[0]?.type).toBe('local-manual-edit'); const divergent = planner.build({ connectorId: 'anilist', direction: 'bidirectional', localEntries: [local({ metadata: { remoteProgress: 8 } })], profileName: 'Default', remoteEntries: [remote()] }); expect(divergent.conflicts[0]?.type).toBe('progress-divergence') })
  it('does not create a remote entry without a verified provider ID', () => { const { plan } = new WatchSyncPlanner().build({ connectorId: 'anilist', direction: 'push', localEntries: [local({ externalIds: {} })], profileName: 'Default', remoteEntries: [] }); expect(plan.operations[0]).toMatchObject({ included: false, type: 'unmatched' }) })
})

describe('sync executor', () => {
  const makePlan = (operations: WatchSyncOperation[], expiresAt = Date.now() + 60_000): WatchSyncPlan => ({ connectorId: 'anilist', createdAt: Date.now(), direction: 'pull', expiresAt, id: crypto.randomUUID(), operations, profileName: 'Default', remoteItemsAnalyzed: 1, summary: { conflicts: 0, createLocal: 1, createRemote: 0, skipped: 0, unchanged: 0, unmatched: 0, updateLocal: 0, updateRemote: 0 } })
  const operation = (type: WatchSyncOperation['type']): WatchSyncOperation => ({ attempt: 0, confidence: 'exact', conflictId: null, error: null, id: crypto.randomUUID(), included: true, localEntry: type === 'create-local' ? null : local(), reason: 'test', remoteEntry: remote(), result: null, state: 'pending', timestamp: null, type })
  it('executes confirmed remote and local operations and reports success', async () => { const executor = new WatchSyncExecutor(); const localHandler = vi.fn().mockResolvedValue(undefined); const remoteHandler = vi.fn().mockResolvedValue('ok'); const operations = [operation('create-local'), operation('update-remote')]; const result = await executor.execute(makePlan(operations), operations.map((item) => item.id), { applyLocal: localHandler, applyRemote: remoteHandler }, new AbortController().signal); expect(result.result).toMatchObject({ failed: 0, succeeded: 2 }); expect(localHandler).toHaveBeenCalledOnce(); expect(remoteHandler).toHaveBeenCalledOnce() })
  it('keeps independent operations running after a network failure', async () => { const executor = new WatchSyncExecutor(); const operations = [operation('update-remote'), operation('update-remote')]; const remoteHandler = vi.fn().mockRejectedValueOnce(new AniListClientError('offline')).mockResolvedValueOnce('ok'); const result = await executor.execute(makePlan(operations), operations.map((item) => item.id), { applyLocal: vi.fn(), applyRemote: remoteHandler }, new AbortController().signal); expect(result.result).toMatchObject({ failed: 1, succeeded: 1 }) })
  it('rejects expired plans and supports cancellation', async () => { const executor = new WatchSyncExecutor(); await expect(executor.execute(makePlan([], Date.now() - 1), [], { applyLocal: vi.fn(), applyRemote: vi.fn() }, new AbortController().signal)).rejects.toThrow(/expiré/); const controller = new AbortController(); controller.abort(); const item = operation('update-remote'); const result = await executor.execute(makePlan([item]), [item.id], { applyLocal: vi.fn(), applyRemote: vi.fn() }, controller.signal); expect(result.result.cancelled).toBe(true); expect(result.operations[0]?.state).toBe('cancelled') })
  it('never needs a real API in tests', () => { const connector = { pullHistory: vi.fn(), pushChange: vi.fn(), testConnection: vi.fn() } as unknown as WatchConnector; expect(connector.pullHistory).not.toHaveBeenCalled() })
})

describe('Gateway and renderer security boundary', () => {
  it('registers unique stubs while keeping unimplemented Simkl capabilities disabled', () => { const registry = new WatchConnectorRegistry(); const ids = registry.list().map((item) => item.id); expect(new Set(ids).size).toBe(ids.length); expect(registry.get('simkl').capabilities.supportsTwoWaySync).toBe(false); expect(new WatchConnectorConfigurationService().get('simkl').clientSecret).toBeNull() })
  it('requires Gateway confirmation before executing a synchronization plan', async () => { const core = new NexusCore(); const manager = { execute: vi.fn() } as unknown as WatchConnectorManager; new WatchConnectorsModule(core.registry, manager).register(); const result = await core.executor.execute({ command: 'watch.sync.execute', createdAt: 1, id: 'watch-sync-command', payload: { confirmedOperationIds: [], syncPlanId: crypto.randomUUID() }, source: 'ui', target: { type: 'local' } }); expect(result.status).toBe('confirmation_required'); expect(manager.execute).not.toHaveBeenCalled() })
  it('rejects unknown connector IDs at the command boundary', async () => { const core = new NexusCore(); const manager = { get: vi.fn() } as unknown as WatchConnectorManager; new WatchConnectorsModule(core.registry, manager).register(); const result = await core.executor.execute({ command: 'watch.connectors.get', createdAt: 1, id: 'watch-connector-command', payload: { connectorId: 'unknown' }, source: 'ui', target: { type: 'local' } }); expect(result.status).toBe('failed'); expect(manager.get).not.toHaveBeenCalled() })
  it('keeps credential field names out of renderer source', async () => { const rendererTypes = await readFile(path.join(process.cwd(), 'src/features/watch-connectors/connector.types.ts'), 'utf8'); expect(rendererTypes).not.toContain('accessToken'); expect(rendererTypes).not.toContain('refreshToken'); expect(rendererTypes).not.toContain('clientSecret') })
})
