import { Icon } from '../../../components/ui/Icon.tsx'
import { WATCH_FILTERS, WATCH_SORTS } from '../../../features/watch-tracking/watch.constants.ts'
import type { WatchEntry, WatchHistoryFilter, WatchHistorySortMode } from '../../../features/watch-tracking/watch.types.ts'
import { WatchSourceBadge } from './WatchSourceBadge.tsx'

function date(value: number | null) { return value ? new Intl.DateTimeFormat('fr-FR', { dateStyle: 'medium' }).format(value) : 'Date inconnue' }

export function UnifiedWatchHistory(props: { entries: readonly WatchEntry[]; filter: WatchHistoryFilter; onFilter: (filter: WatchHistoryFilter) => void; onQuery: (query: string) => void; onSelect: (id: string) => void; onSort: (sort: WatchHistorySortMode) => void; query: string; selectedId: string | null; sort: WatchHistorySortMode }) {
  return <section className="unified-watch-history"><header><div><span>UNIFIED WATCH HISTORY</span><h2>Les traces de visionnage</h2></div><small>{props.entries.length} entrées visibles</small></header><div className="watch-history-toolbar"><label><Icon name="search" size={15} /><input onChange={(event) => props.onQuery(event.target.value)} placeholder="Titre, série, épisode, source ou profil" value={props.query} /></label><div>{WATCH_FILTERS.map((entry) => <button aria-pressed={props.filter === entry.id} className={props.filter === entry.id ? 'is-active' : ''} key={entry.id} onClick={() => props.onFilter(entry.id)} type="button">{entry.label}</button>)}</div><select aria-label="Trier l’historique" onChange={(event) => props.onSort(event.target.value as WatchHistorySortMode)} value={props.sort}>{WATCH_SORTS.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select></div>{props.entries.length > 0 ? <ol className="watch-timeline">{props.entries.map((entry) => <li className={props.selectedId === entry.id ? 'is-selected' : ''} key={entry.id}><button onClick={() => props.onSelect(entry.id)} type="button"><span className="watch-timeline-node"><i /></span><span className="watch-timeline-copy"><WatchSourceBadge precision={entry.progress.precision} provider={entry.primaryProvider} /><strong>{entry.title}</strong><small>{entry.seriesTitle ? `${entry.seriesTitle}${entry.seasonNumber !== null ? ` · S${entry.seasonNumber}` : ''}${entry.episodeNumber !== null ? ` E${entry.episodeNumber}` : ''}` : entry.mediaType}</small></span><span className="watch-timeline-state"><b>{entry.status}</b><small>{entry.progress.percent === null ? 'Progression inconnue' : `${Math.round(entry.progress.percent)} %`}</small></span><time>{date(entry.watchedAt)}</time></button></li>)}</ol> : <div className="watch-history-empty"><Icon name="clock" size={26} /><strong>Aucune trace dans cette clairière.</strong><p>Importez un historique, ajoutez une entrée manuelle ou lancez un média depuis NEXUS.</p></div>}</section>
}
