import { useEffect, useState } from 'react'

import { Icon } from '../../../components/ui/Icon.tsx'
import type { WatchEntry, WatchEntryUpdate, WatchStatus } from '../../../features/watch-tracking/watch.types.ts'
import { WatchSourceBadge } from './WatchSourceBadge.tsx'

function dateInput(timestamp: number | null) { return timestamp ? new Date(timestamp).toISOString().slice(0, 10) : '' }

export function WatchDetailsPanel({ entry, onDelete, onMark, onUpdate }: { entry: WatchEntry | null; onDelete: (id: string) => void; onMark: (id: string, status: WatchStatus) => void; onUpdate: (id: string, changes: WatchEntryUpdate) => void }) {
  const [editing, setEditing] = useState(false)
  useEffect(() => setEditing(false), [entry?.id])
  if (!entry) return <aside className="watch-details watch-details-empty"><Icon name="film" size={27} /><strong>Sélectionnez une trace</strong><p>Sa provenance, sa précision et ses actions apparaîtront ici.</p></aside>
  return <aside className="watch-details"><header><span>MEDIA DETAILS</span><button aria-label="Modifier" onClick={() => setEditing((value) => !value)} type="button"><Icon name="settings" size={14} /></button></header><WatchSourceBadge precision={entry.progress.precision} provider={entry.primaryProvider} /><h2>{entry.title}</h2><p>{entry.seriesTitle ?? entry.originalTitle ?? 'Entrée indépendante'}</p><dl><div><dt>Profil</dt><dd>{entry.profileName}</dd></div><div><dt>Statut</dt><dd>{entry.status}</dd></div><div><dt>Progression</dt><dd>{entry.progress.percent === null ? 'Inconnue' : `${Math.round(entry.progress.percent)} %`}</dd></div><div><dt>Précision</dt><dd>{entry.progress.precision}</dd></div><div><dt>Confiance</dt><dd>{entry.confidence}</dd></div><div><dt>Modification</dt><dd>{entry.manuallyEdited ? 'Manuelle' : 'Source'}</dd></div></dl>{editing && <form onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const season = data.get('season'); const episode = data.get('episode'); const watchedAt = data.get('watchedAt'); onUpdate(entry.id, { episodeNumber: episode ? Number(episode) : null, seasonNumber: season ? Number(season) : null, title: String(data.get('title') ?? entry.title), watchedAt: watchedAt ? new Date(String(watchedAt)).getTime() : null }); setEditing(false) }}><label>Titre<input defaultValue={entry.title} name="title" required /></label><div><label>Saison<input defaultValue={entry.seasonNumber ?? ''} min="0" name="season" type="number" /></label><label>Épisode<input defaultValue={entry.episodeNumber ?? ''} min="0" name="episode" type="number" /></label></div><label>Date<input defaultValue={dateInput(entry.watchedAt)} name="watchedAt" type="date" /></label><button type="submit"><Icon name="check" size={13} />Enregistrer la correction</button></form>}<div className="watch-details-actions"><button onClick={() => onMark(entry.id, 'completed')} type="button"><Icon name="check" size={13} />Marquer vu</button><button onClick={() => onMark(entry.id, 'in-progress')} type="button"><Icon name="play" size={13} />En cours</button><button onClick={() => onMark(entry.id, 'planned')} type="button">Non vu</button></div><footer><span>{entry.sources.length} source{entry.sources.length > 1 ? 's' : ''} conservée{entry.sources.length > 1 ? 's' : ''}</span><button onClick={() => onDelete(entry.id)} type="button">Supprimer</button></footer></aside>
}
